# Generated by Django 5.2 on 2025-12-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
