# Generated by Django 5.2 on 2026-01-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='district',
            field=models.CharField(choices=[('Hong Kong Island', [('CW', 'Central & Western'), ('ER', 'Eastern'), ('SR', 'Southern'), ('WC', 'Wan Chai')]), ('Kowloon', [('KC', 'Kowloon City'), ('KW', 'Kwun Tong'), ('SS', 'Sham Shui Po'), ('WT', 'Wong Tai Sin'), ('YM', 'Yau Tsim Mong')]), ('New Territories', [('IL', 'Islands'), ('KT', 'Kwai Tsing'), ('NR', 'North'), ('SK', 'Sai Kung'), ('ST', 'Sha Tin'), ('TP', 'Tai Po'), ('TW', 'Tsuen Wan'), ('TM', 'Tuen Mun'), ('YL', 'Yuen Long')])], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='room_type',
            field=models.CharField(choices=[('Private Rooms', 'Private Rooms'), ('Semi-Private Rooms', 'Semi-Private Rooms'), ('Standard (Multi-bed) Rooms', 'Standard (Multi-bed) Rooms')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rooms',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], max_length=2),
        ),
    ]
